#! /bin/bash
set -x
set -e
. ./bin/ascii_art

# May set zypp-LABEL if ~/zypp-ci-label does not exist (otherwise change manually)
test -n "$1" && {
  echo "$1" >~/zypp-ci-label					|| ascii_bad
  chmod 444 ~/zypp-ci-label					|| ascii_bad
}
test -f ~/zypp-ci-label						|| ascii_bad
head -n 1 ~/zypp-ci-label | grep -q '^zypp-[a-z0-9._-]\+$'	|| ascii_bad

# Setup some rc and config files..
for C in hostsetup.d/*; do
  . $C || ascii_bad
done

# Repos and packages are usually setup only once.
# Omit them if Jenkins is already working...
test -d ~/hudson/workspace || {
  DEVELPKGS="augeas-devel"
  DEVELPKGS="$DEVELPKGS boost-devel"
  DEVELPKGS="$DEVELPKGS cmake curl-devel"
  DEVELPKGS="$DEVELPKGS db-devel dejagnu doxygen"
  DEVELPKGS="$DEVELPKGS expat expat-devel"
  DEVELPKGS="$DEVELPKGS fdupes"
  DEVELPKGS="$DEVELPKGS gcc-c++ gettext-devel glib2-devel graphviz"
  DEVELPKGS="$DEVELPKGS hal-devel"
  DEVELPKGS="$DEVELPKGS icecream"
  DEVELPKGS="$DEVELPKGS libcurl-devel libexpat-devel libproxy-devel librpm-devel libxml2-devel"
  DEVELPKGS="$DEVELPKGS ntp"
  DEVELPKGS="$DEVELPKGS openssl-devel osc"
  DEVELPKGS="$DEVELPKGS perl-devel pkg-config popt-devel python-devel"
  DEVELPKGS="$DEVELPKGS protobuf-devel"
  DEVELPKGS="$DEVELPKGS readline-devel rpm-devel ruby-devel"
  DEVELPKGS="$DEVELPKGS swig"
  DEVELPKGS="$DEVELPKGS yaml-cpp-devel"
  DEVELPKGS="$DEVELPKGS zlib-devel libzck-devel"

  # Prepare the repos
  rm -f /etc/zypp/repos.d/*
  case "$Z_LABEL" in
    head)
      zypper ar -f	http://download.opensuse.org/tumbleweed/repo/oss/			tw-oss
      zypper ar -f	http://download.opensuse.org/tumbleweed/repo/non-oss/			tw-non-oss
      ;;
    s15)
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-15:/GA/standard/			$Z_LABEL-GA
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-15:/Update/standard/			$Z_LABEL-UPD
      ;;
    s12sp3)
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-12-SP3:/GA/standard/			$Z_LABEL-GA
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-12-SP3:/Update/standard/		$Z_LABEL-UPD
      ;;
    s12sp2)
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-12-SP2:/GA/standard/			$Z_LABEL-GA
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-12-SP2:/Update/standard/		$Z_LABEL-UPD
      ;;
    s12sp1)
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-12-SP1:/GA/standard/			$Z_LABEL-GA
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-12-SP1:/Update/standard/		$Z_LABEL-UPD
      ;;
    s12)
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-12:/GA/standard/			$Z_LABEL-GA
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-12:/Update/standard/			$Z_LABEL-UPD
      ;;
    s11sp3)
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-11-SP4::/GA/standard/			$Z_LABEL-GA
      zypper ar -f	http://dist.suse.de/ibs/SUSE:/SLE-11-SP4::/Update/standard/		$Z_LABEL-UPD
      ;;
  esac
  zypper lr -u
  zypper --gpg-auto-import-keys ref -f
  zypper in $DEVELPKGS
}

ascii_good
exit 0
