#! /bin/bash
################################################################################
# Colored echo output
################################################################################
# ISO 6429 color sequences are composed of sequences of
# numbers separated by semicolons.  The most common codes are:
#    0     to restore default color
#    1     for brighter colors
#    4     for underlined text
#    5     for flashing text
#   30     for black foreground
#   31     for red foreground
#   32     for green foreground
#   33     for yellow (or brown) foreground
#   34     for blue foreground
#   35     for purple foreground
#   36     for cyan foreground
#   37     for white (or gray) foreground
#   40     for black background
#   41     for red background
#   42     for green background
#   43     for yellow (or brown) background
#   44     for blue background
#   45     for purple background
#   46     for cyan background
#   47     for white (or gray) background
# ############################################################

function __echostr() {
    if [ "$1" == "printf" ]; then
	"$@"
    else
	echo -n "$*"
    fi
}
function __cechostr() {
    local C="$1"; shift
    local N;
    case "$1" in
	-n)	N='-n'; shift;;
	#printf)	N='-n';;
    esac
    echo $N -e "$C$(__echostr "$@")\e[0m";
}
export -f __cechostr __echostr

function Recho()  { __cechostr "\e[0;31m" "$@"; }
function Gecho()  { __cechostr "\e[0;32m" "$@"; }
function Becho()  { __cechostr "\e[0;34m" "$@"; }
function Cecho()  { __cechostr "\e[0;36m" "$@"; }
function Mecho()  { __cechostr "\e[0;35m" "$@"; }
function Yecho()  { __cechostr "\e[0;33m" "$@"; }
function BLecho() { __cechostr "\e[0;30m" "$@"; }
function WHecho() { __cechostr "\e[1;37m" "$@"; }
export -f Recho Gecho Becho Cecho Mecho Yecho BLecho WHecho
