#! /bin/bash
set -e

[ type -t Recho ] || {
    # Colored echo output if you don't have it
    function __echostr() {
        if [ "$1" == "printf" ]; then
            "$@"
        else
            echo -n "$*"
        fi
    }
    function __cechostr() {
        local C="$1"; shift
        local N;
        case "$1" in
            -n)	N='-n'; shift;;
            #printf)	N='-n';;
        esac
        echo $N -e "$C$(__echostr "$@")\e[0m";
    }
    export -f __cechostr __echostr

    function Recho()  { __cechostr "\e[0;31m" "$@"; }
    function Gecho()  { __cechostr "\e[0;32m" "$@"; }
    function Becho()  { __cechostr "\e[0;34m" "$@"; }
    function Cecho()  { __cechostr "\e[0;36m" "$@"; }
    function Mecho()  { __cechostr "\e[0;35m" "$@"; }
    function Yecho()  { __cechostr "\e[0;33m" "$@"; }
    function BLecho() { __cechostr "\e[0;30m" "$@"; }
    function WHecho() { __cechostr "\e[1;37m" "$@"; }
    export -f Recho Gecho Becho Cecho Mecho Yecho BLecho WHecho
}
PFX="    "  # for indented printing
function Bhead()
{
    if (( $# )); then
        Becho "$(cut -c -80 <<<"$@================================================================================")"
    else
        Becho
    fi
}
function DBG() {
    # suppress echo unless DEBUG is set
    if (( $DEBUG )); then
        "$@"
    fi
}
function REM() {
    # echo now and remember for summary
    local OUT="$("$@")"
    REMEMBER+=("$OUT")
    echo "$OUT"
}


function GIT()
{ git -C $GDIR "$@"; }

function VGIT() {
    Cecho "[GIT> $@"
    if (( $DEBUG )); then
        GIT "$@"
    else
        GIT "$@" >/dev/null
    fi
}


function gitCurrentBranch()
{ GIT rev-parse --abbrev-ref HEAD; }

function isLocalBranch()
{ GIT show-ref heads/"$1" >/dev/null; }

function gitStrictAncestor()
{
    # strict: return 0 if equal and fail if unrelated
    local C1="$1"
    local C2="$2"
    local RES=""
    if GIT merge-base --is-ancestor "$C1" "$C2"; then
        RES="${RES}1"
    else
        RES="${RES}0"
    fi
    if GIT merge-base --is-ancestor "$C2" "$C1"; then
        RES="${RES}1"
    else
        RES="${RES}0"
    fi
    case $RES in
        00)
            Recho "$C1 ? $C2 : unrelated"
            false
            ;;
        01)
            # Becho "$C1 > $C2"
            return 0
            ;;
        10)
            # Becho "$C1 < $C2"
            ;;
        11)
            # Becho "$C1 = $C2 : equal"
            ;;
        *)
            Recho "OOps"
            false
            ;;
    esac
    return 1
}

function pDescribe()	# [-> _VAR branch ID]
{
    local B="$1"
    local BID="$(GIT describe --always --long "$B")"
    if [[ -n $2 ]]; then
        local -n _VAR=$2	# to return branch ids
	_VAR="$BID"
    else
        Cecho "$BID $B"
    fi
}

function pLogRange()
{ GIT log --oneline "$1"; }


function _diffOldNewContent()
{
    local OLD="$1"
    local NEW="$2"
    # may want to ignore changes in .git* files
    GIT diff --name-status "$OLD" "$NEW" | grep -v '^..\.git'
}

function pDiff()     #  [-> _RET 0/1 if same/differ]
{
    local OLD="$1"
    local NEW="$2"
    local -n _RET="$3"

    local -a CMDOUT
    readarray -t CMDOUT < <(_diffOldNewContent "$OLD" "$NEW")
    if (( ${#CMDOUT[@]} )); then
        _RET=1
        Becho "$PFX""# $OLD and $NEW differ"
    else
        _RET=0
        Becho "$PFX""# No difference between $OLD and $NEW"
    fi
}

function pLogDiff()     #  [-> _RET 0/1 if same/differ]
{
    local OLD="$1"
    local NEW="$2"
    local -n _RET="$3"

    local O N
    pDescribe "$OLD" "O"
    pDescribe "$NEW" "N"

    Bhead "### ===[ $GDIR ]( $OLD <> $NEW )================================="
    if [[ $O = $N ]]; then
        _RET=0
        Becho "$PFX""# $OLD is up-to-date with $NEW at $O"
    else
	local O2C=$(pLogRange "$OLD..$NEW" | wc -l)    # OLD -> common ancestor
	local C2N=$(pLogRange "$NEW..$OLD" | wc -l)    # common ancestor -> NEW
        Becho "$PFX""# $OLD at $O ->($O2C)($C2N)-> $NEW at $N"

        local -a CMDOUT
        readarray -t CMDOUT < <(_diffOldNewContent "$OLD" "$NEW")
        if (( ${#CMDOUT[@]} )); then
            _RET=1
            for X in "${CMDOUT[@]}"; do
                case "$X" in
                    A*)
                        Gecho "$PFX""$X"
                        ;;
                    D*)
                        Recho "$PFX""$X"
                        ;;
                    M*)
                        Becho "$PFX""$X"
                        ;;
                    *)
                        echo "$PFX""$X"
                        ;;
                esac
            done
        else
            _RET=0
            Becho "$PFX""# No difference between $OLD and $NEW"
        fi

        if (( $O_SHOWCHANGES )); then
            readarray -t CMDOUT < <(GIT diff "$OLD" "$NEW" "*changes")
            for X in "${CMDOUT[@]}"; do
                case "$X" in
                    ++*) ;;
                    --*) ;;
                    +*)
                        Gecho "$PFX""$X"
                        ;;
                    -*)
                        Recho "$PFX""$X"
                        ;;
                    @@*)
                        Cecho "$PFX""$X"
                        ;;
                    *)
                        #echo "$PFX""$X"
                        ;;
                esac
            done
        fi
    fi
}

function pLogPRStat()   # [-> _RET 0/1 whether an own(!) PR is open
{
    local BRANCH="$1"
    local SOURCE="$BRANCH"   # our gitea WF expects PRs from the same branch name
    local -n _RET="$2"
    local -n _RUNNING_PRS="$3"

    local -a CMDOUT
    local CURRENT_ID
    _RUNNING_PRS=()
    readarray -t CMDOUT < <($GITOBS pr list --state open --target-branch $BRANCH pool/$PKG 2>/dev/null)
    if (( ${#CMDOUT[@]} )); then
        _RET=0  # preliminary assume no own PR open
        Becho "$PFX""# Pending PRs for pool/$PKG $BRANCH:"
        local -i MY_PR
        for X in "${CMDOUT[@]}"; do
            case "$X" in
                ID*)
                    MY_PR=1 # a new block PR data
                    CURRENT_ID=${X#*:}
                    ;;
                Author*)
                    [[ $X =~ ": $GITEAUSER" ]] || {
                        Mecho "$PFX""$X"" [not $GITEAUSER]"
                        MY_PR=0
                        continue
                    }
                    ;;
                Source*)
                    X="$(sed 's/^\(.*commit:.......\).*/\1/' <<<"$X")"
                    [[ $X =~ ": $GITEAUSER/$PKG, branch: $SOURCE" ]] || {
                        Mecho "$PFX""$X"" [not $GITEAUSER/$PKG $SOURCE]"
                        MY_PR=0
                        continue
                    }
                    ;;
                Target*)
                    X="$(sed 's/^\(.*commit:.......\).*/\1/' <<<"$X")"
                    ;;
                Description*)
                    # PR data block ends
                    if (( $MY_PR )); then
                        _RET=1
                        Gecho "$PFX""# It's my PR!"
                        _RUNNING_PRS+=($(Gecho "$CURRENT_ID"))
                    else
                        Recho "$PFX""# It's a foreign PR!"
                        _RUNNING_PRS+=($(Recho "$CURRENT_ID"))
                    fi
                    break   # hides the description
                    ;;
                *)
                    ;;
            esac
            echo "$PFX""$X"
        done
    else
        _RET=0
        Becho "$PFX""# No open PRs for pool/$PKG $BRANCH"
    fi
}

### ============================================================
### Global vars available within the commands:
###   OBS     "obs" or "ibs"; for git-obs to refer to the right server
###   GITOBS  git-obs command to refer to the right server (git-obs git-ibs)
###
###   PKG   the package to process
###   GDIR  "$OBS/$PKG"; subdirectory of the local clone
###   GIT   "git -C $GDIR" git command to address the local clone
###
### Expecting CWD to be the parent dir of "obs" and "ibs"
#
function assertClone()
{
    [ -d "$GDIR/.git" ] || {
	Mecho "# Create initial clone from fork ($GITOBS repo fork pool/$PKG)"
	# Expect "$OBS" to be created manually. Don't clutter arbitrary CWDs
	( cd "$OBS"; $GITOBS repo clone $GITEAUSER/$PKG ) || {
	    Recho "Missing fork ($GITOBS repo fork pool/$PKG)?"
	    return 1
	}
    }
}

function isMergeCommit()
{
    local MERGE="$1"
    local PARENT1="$2"
    local PARENT2="$3"

    local MP1 MP2 P1 P2
    pDescribe $MERGE^1 "MP1"
    pDescribe $MERGE^2 "MP2"
    pDescribe $PARENT1 "P1"
    pDescribe $PARENT2 "P2"
    DBG Cecho "# $MERGE($MP1|$MP2) <?< $PARENT1($P1) | $PARENT2)$P2)"
    [[ $MP1 = $P1 && $MP2 = $P2 ]]
}

function checkFetch()
{
    local THRESHOLD=$((${1:-60}))	# Threshold in minutes until next unforced fetch
    local FETCH_LOG="$GDIR/.git/FETCH_HEAD"

    if [ ! -f "$FETCH_LOG" ]; then
	Cecho "# No fetch history found. Fetching now..."
    else
	if (( "$FORCE" )); then
	    Cecho "# FORCE fetching now..."
	elif [ -n "$(find "$FETCH_LOG" -mmin +"$THRESHOLD")" ]; then
	    Cecho "# Last fetch was over $THRESHOLD minutes ago. Updating..."
	else
	    Mecho "# Fetch skipped. Data is still fresh (less than $THRESHOLD min old)."
	    return
	fi
    fi
    VGIT fetch --porcelain --all
}

function getPRTargets() # [-> _ARRAY to return possible PR targets]
{
    local -n _ARRAY=$1
    local PATTERN=''
    case "$OBS" in
	obs)
	    PATTERN='^parent/leap'
	    ;;
	ibs)
	    PATTERN='^parent/slfo'
	    ;;
	*)
	    Recho "Unknown value for OBS: $OBS"
	    return 1
	    ;;
    esac
    while read X; do
	[[ $X =~ ^parent/HEAD ]] && continue
	if [[ $X =~ $PATTERN ]]; then
	    DBG Cecho "+ $X"
	    _ARRAY+=("$X")
	else
	    DBG Yecho "  $X"
	fi
    done <<<$(GIT branch -r --list 'parent/*')
}

function getLeadInPRTargets() # [-> _LEAD, -> _ARRAY with _LEAD stripped ]
{
    # Force one LEAD and multiple ancestors.
    # No support for unrelated branches in the array.
    local -n _LEAD=$1
    local -n _ARRAY=$2
    shift 2

    _LEAD=''
    _ARRAY=()
    local BRANCH=''
    for BRANCH in $@; do
        if [[ -z $_LEAD ]]; then
            _LEAD=$BRANCH
        else
            if gitStrictAncestor $BRANCH $_LEAD; then
                _ARRAY+=($_LEAD)
                _LEAD=$BRANCH
            else
                _ARRAY+=($BRANCH)
            fi
        fi
    done
}

function assertBranchAt()
{
    local BRANCH=$1
    local STARTPOINT=$2
    local MYBRANCH=$(gitCurrentBranch)

    if isLocalBranch $BRANCH; then
        VGIT checkout $BRANCH
    else
        VGIT checkout -b $BRANCH
    fi
    VGIT reset --hard $STARTPOINT
}

function mergeFrom()
{
    # Gitea sometimes separates the factory branch.
    # https://suse.slack.com/archives/C03FJGXPNF9/p1771269462786729
    local BRANCH=$1
    VGIT merge --no-edit --allow-unrelated-histories -X theirs $BRANCH

    # Due to -X theirs we need to remove excess files (old tarballs).
    # Diff goes old:$BRANCH new:local, so excess files appear as (A)dded.
    local -a CMDOUT
    readarray -t CMDOUT < <(GIT diff --name-status $BRANCH)
    for X in "${CMDOUT[@]}"; do
        case "$X" in
            A*)
                Mecho "[-X theirs:remove excess] $X"
                VGIT rm "${X#$'A\t*'}"
                VGIT commit --no-edit --amend
                ;;
            *)
                Recho "[unexpected diff] $X"
                return 1
                ;;
        esac
    done
}

function forceSyncBranch()
{
    local BRANCH="$1"
    local MYBRANCH="$(gitCurrentBranch)"
    if [[ $MYBRANCH = $BRANCH ]]; then
	DBG Cecho "# On branch $MYBRANCH"
    else
	Recho "OOPS: Local branch $MYBRANCH is not $BRANCH (missing assertBranch?)"
	return 1 # error out! (missing assertBranch?)
    fi

    local L O
    pDescribe $BRANCH "L"
    pDescribe origin/$BRANCH "O"
    if [[ $L != $O ]]; then
        Cecho "# Updating $BRANCH to origin"
        # If unneeded tarballs are missing:
        # git config lfs.allowincompletepush true
        VGIT push --force origin $BRANCH
        pDescribe origin/$BRANCH "O"
    fi

    [[ $L != $O ]] && {
	Recho "OOPS: Not up-to date after push: $BRANCH: local:$L origin:$O"
	retrun 1 # error out! (failed push)
    }

    Becho "# Up-to date after push: origin:$O"
}

function fileNewPR()
{
    local REPO="$1"
    local SRC_BRANCH="${2#*/}"
    local TRG_BRANCH="${3#*/}"

    Cecho "REPO:       $REPO"
    Cecho "SRC_BRANCH: $SRC_BRANCH"
    Cecho "TRG_BRANCH: $TRG_BRANCH"

    $GITOBS pr create \
        --source-owner  "$GITEAUSER" \
        --source-repo   "$REPO" \
        --source-branch "$SRC_BRANCH" \
        --target-branch "$TRG_BRANCH" \
        --title "Update $TRG_BRANCH to factory version." --description ""
}


function updateStats()
{
    assertClone
    checkFetch 60

    MYTARGETS=()
    getPRTargets MYTARGETS
    (( ${#MYTARGETS[@]} )) || {
	Mecho "# No PR targets!"
	return
    }
    Becho "# Found ${#MYTARGETS[@]} PR targets!"
    # We want to merge factory(FF) into the product branches (PN).
    # So we expect there's one "lead" product branch and all other product
    # branches are ancestors of the "lead" (or equal).
    #
    #      ...FF        ...FF'        ...FF''
    #           \            \             \
    #     ...O---P1---O---O---P2            merge(P2|FF'')
    #              \         /  \          /
    #   - old PR:   +_P1_PR_+    \        /    }
    #   + new PR:    \            +_P2_PR+      } on --commit only
    #   + amended PR: +_____P1_PR_______+      }
    #
    # We merge the "lead" (local) and file/amend it's PR (origin->parent).
    # The other branches we force reset (local and origin) to the "lead"
    # and file/amend their PRs.
    local LEAD=''
    local -a ANCESTORS
    getLeadInPRTargets "LEAD" "ANCESTORS" ${MYTARGETS[@]}

    local LEAD_BRANCH=${LEAD#*/}
    for DEST in $LEAD ${ANCESTORS[@]}; do
        local TARGET_BRANCH=${DEST#*/}
        Bhead

        if [[ $TARGET_BRANCH = $LEAD_BRANCH ]]; then
            Bhead "# [ $GDIR $TARGET_BRANCH (LEAD)]"
            # Merge parent factory if needed:
            # Local LEAD should be the merge of parent/LEAD and parent/factory,
            # if it differs from origin/LEAD, otherwise origin/LEAD (last PR).
            # NOTE: "differs" here means added/removed/modified files (except .git*)
            if isMergeCommit origin/$TARGET_BRANCH parent/$TARGET_BRANCH parent/factory; then
                Becho "# origin/$TARGET_BRANCH is merge of parent/$TARGET_BRANCH and parent/factory"
                assertBranchAt $TARGET_BRANCH origin/$TARGET_BRANCH
            else
                Becho "# Create $TARGET_BRANCH as merge of parent/$TARGET_BRANCH and parent/factory"
                assertBranchAt $TARGET_BRANCH parent/$TARGET_BRANCH
                mergeFrom parent/factory
            fi
        else
            Bhead "# [ $GDIR $TARGET_BRANCH (ANCESTOR)]"
            # Follow the LEAD branch (was updated first):
            Becho "# Follow the LEAD branch $LEAD_BRANCH"
            assertBranchAt $TARGET_BRANCH $LEAD_BRANCH
        fi

        # Now check the banch's fate::
        # parent/factory -> TARGET_BRANCH -> origin/TARGET_BRANCH -> parent/TARGET_BRANCH
        #                   ^                         ^                ^
        #                   |___ORIGIN_NEEDS_UPDATE___|___PR_RUNNING___|
        #                   |_________________DO_DIFFER________________|
        pLogDiff parent/$TARGET_BRANCH $TARGET_BRANCH DO_DIFFER
        pLogPRStat $TARGET_BRANCH                     PR_RUNNING RUNNING_PRS
        pDiff    origin/$TARGET_BRANCH $TARGET_BRANCH ORIGIN_NEEDS_UPDATE

        # wrap it up:
        # NOTE: PR_RUNNING refers to OWN PRs only. RUNNING_PRS may contain foreign PRs
        #       that's why its always printed.
        Bhead "$PFX""### ==================================================="
        if (( $DO_DIFFER )); then
            if (( $ORIGIN_NEEDS_UPDATE )); then
                if (( $PR_RUNNING )); then
                    REM Mecho "$PFX""### $GDIR $DEST:\tUPDATE_ORIGIN (pr_is_running) ${RUNNING_PRS[@]}"
                    (( DO_SUBMIT )) && {
                        forceSyncBranch $TARGET_BRANCH
                    }
                else
                    REM Mecho "$PFX""### $GDIR $DEST:\tUPDATE_ORIGIN and FILE_NEW_PR  ${RUNNING_PRS[@]}"
                    (( DO_SUBMIT )) && {
                        forceSyncBranch $TARGET_BRANCH
                        fileNewPR $PKG origin/$TARGET_BRANCH $DEST
                    }
                fi
            else
                if (( $PR_RUNNING )); then
                    REM Becho "$PFX""### $GDIR $DEST:\tis fine! (pr_is_running) ${RUNNING_PRS[@]}"
                else
                    REM Mecho "$PFX""### $GDIR $DEST:\tFILE_NEW_PR  ${RUNNING_PRS[@]}"
                    (( DO_SUBMIT )) && {
                        forceSyncBranch $TARGET_BRANCH
                        fileNewPR $PKG origin/$TARGET_BRANCH $DEST
                    }
                fi
            fi
        else
            REM Becho "$PFX""### $GDIR $DEST:\tis fine!"
        fi
        Bhead "$PFX""### ==================================================="
    done
}

### ============================================================
### ============================================================
function usage() {
    cat << EOF
Usage: $(basename "$0") [OPTS..] [PKG..] [-- GITARGS..]

Options:
    -f  Force git fetch (otherwise once an hour)
    -v  More verbose; e.g. show all parent branches
Dangerzone:
    --submit
        Updates or files required PRs (syncs local to origin/local).

PreReq:
- GITEAUSER configured: "$GITEAUSER"
- PKGS configured: ${PKGS[@]}
- Set up 'git-obs' and 'git-ibs' commands to refer to src.suse and src.opensuse.
- Set up 'osc' and 'isc' commands to refer OBS and IBS.
- Create empty 'obs' and 'ibs' subdirectories. We use them for cloning the repos.
- Login to src.suse and src.opensuse and fork the packages from pool/PKG.
  (or do it on the command line; the script will hint if a fork is missing)

  # We want to merge factory(FF) into the product branches (PN).
  #
  #      ...P1...P2
  # 	   ..FF
  #
  # We'd like to have P1==P2, but unfortunately we cant influence how fast
  # the products merge pending PRs. Additionally there's no guarantee that
  # FF (synced from src.opensuse) and the product branches share a common
  # history.
  #
  # Anyway, if we'd merge each product branch independently we'd separate
  # the branches. That's actually not wrong, but disguises that the separated
  # branches are actually the same:
  #
  #            +-----------merge(P1|FF)...
  #           /           /
  #      ...P1...P2   ..FF
  #                \      \
  #                 +------merge(P2|FF)...
  #
  # So we expect there's one "lead" product branch and all other product
  # branches are ancestors of (or equal to) the "lead" .
  #
  #      ...FF        ...FF'        ...FF''
  #           \            \             \
  #     ...O---P1---O---O---P2            merge(P2|FF'')
  #              \         /  \          /
  #   - old PR:   +_P1_PR_+    \        /    }
  #   + new PR:    \            +_P2_PR+      } on --commit only
  #   + amended PR: +_____P1_PR_______+      }
  #
  # We merge the "lead" (local) and file/amend it's PR (origin->parent).
  # The other branches we force reset (local and origin) to the "lead"
  # and file/amend their PRs.
  #
  # NOTE: Without --commit we will not move origin/ branches nor file
  #       PRs. We will just adjust the local branches to check whether
  #       changes are pending (whether --commit would amend or file new PRs).

Recognized PR targets are:
    obs: parent/leap*
    ibs: parent/slfo*

We skip "obs" per default because there are no leap* branches for our packages.
Use "-v obs all" to check obs.

Without PKG args it checks the core stack only (libsolv, libzypp, zypper).
Pass package names to check specific packages or use "all".

[If "-- GITARGS.." is passed, this git command is executed in all repos rather
checking it's status]
EOF
}
### ============================================================
### ============================================================
GITEAUSER="${GITEAUSER:-"mlandres"}"
DO_SUBMIT=$((${DO_SUBMIT:-0}))
FORCE=$((${FORCE:-0}))
DEBUG=$((${DEBUG:-0}))
REMEMBER=() # summary
O_SHOWCHANGES=$((${O_SHOWCHANGES:-1}))

PKGS=("libsolv" "libzypp" "zypper" "libzypp-testsuite-tools" "zypp-plugin")
function containsPKG() { [[ " ${PKGS[*]} " =~ " $1 " ]]; }

[ -d "obs" -o -d "ibs" ] || {
    usage
    Recho "Neither 'obs' nor 'ibs' subdirectory exists. Wrong CWD?"
    false
}

obs=("ibs")
pkg=()
for ARG in "$@"; do
    case "$ARG" in
        --help|-h|help)
            usage
            exit
            ;;
        -v)
            DEBUG=1
            ;;
        -f)
            FORCE=1
            ;;
        --submit)
            DO_SUBMIT=1
            FORCE=1 # force fetch
            ;;
        obs)
            obs=("obs")
            ;;
        all)
            pkg=("${PKGS[@]}")
            ;;
        --)
            shift
            break   # leave it in $@
            ;;
        *)
            if containsPKG "$ARG"; then
                pkg+=("$ARG")
            else
                Recho "Unknown ARG $ARG"
                false
            fi
            ;;
    esac
    shift
done
(( ${#pkg[@]} )) || {
    pkg=("libsolv" "libzypp" "zypper")
}

for OBS in "${obs[@]}"; do
    Bhead
    Bhead "### ===[ $OBS ]============================================="
    GITOBS="git-$OBS"
    for PKG in "${pkg[@]}"; do
	GDIR="$OBS/$PKG"
	Bhead
	Bhead "### ==================================================="
	Bhead "### ===[ $GDIR ]( $@ )================================="

	if (( ! $# )); then
	    updateStats
	else
	    GIT "$@" || Recho "$?"
	fi
    done
done

if (( ${#REMEMBER[@]} )); then
    Becho
    Bhead "### ==================================================="
    Becho "### Summary:"
    for L in "${REMEMBER[@]}"; do
        echo "$L"
    done
fi
