# See README for details
services:
    zci-tw:
        image: zci-tw
        volumes:
            - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
            - $CI_ROOT_VOLUME:$CI_ROOT_VOLUME
            - ciroot:/home/zci/ZCIWorkspace
        environment:
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - CI_BUILDROOT=/home/zci/ZCIWorkspace
            - CI_ROOT=$CI_ROOT_VOLUME
            - CI_PRJ=head
        extra_hosts:
            dist.suse.de: $DIST_SUSE_DE
        build:
            context: .
            dockerfile: tw.Dockerfile
            args:
                - CI_UID=${CI_UID}
                - CI_GID=${CI_GID}
            extra_hosts:
                dist.suse.de: $DIST_SUSE_DE
        profiles:
            - all
            - tw


    zci-s15-latest:
        image: zci-s15-latest
        volumes:
            - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
            - $CI_ROOT_VOLUME:$CI_ROOT_VOLUME
            - ciroot:/home/zci/ZCIWorkspace
        environment:
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - CI_BUILDROOT=/home/zci/ZCIWorkspace
            - CI_ROOT=$CI_ROOT_VOLUME
            - CI_PRJ=s15sp4
        extra_hosts:
            dist.suse.de: $DIST_SUSE_DE
        build:
            context: .
            dockerfile: s15-latest.Dockerfile
            args:
                - CI_UID=${CI_UID}
                - CI_GID=${CI_GID}
            extra_hosts:
                dist.suse.de: $DIST_SUSE_DE
        profiles:
            - s15


    zci-s12-latest:
        image: zci-s12-latest
        volumes:
            - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
            - $CI_ROOT_VOLUME:$CI_ROOT_VOLUME
            - ciroot:/home/zci/ZCIWorkspace
        environment:
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - CI_BUILDROOT=/home/zci/ZCIWorkspace
            - CI_ROOT=$CI_ROOT_VOLUME
            - CI_PRJ=s12sp2
        extra_hosts:
            dist.suse.de: $DIST_SUSE_DE
        build:
            context: .
            dockerfile: s12-latest.Dockerfile
            args:
                - CI_UID=${CI_UID}
                - CI_GID=${CI_GID}
            extra_hosts:
                dist.suse.de: $DIST_SUSE_DE
        profiles:
            - all
            - s12


    # Dockerfile builds on s12!
    zci-s11-latest:
        image: zci-s11-latest
        volumes:
            - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
            - $CI_ROOT_VOLUME:$CI_ROOT_VOLUME
            - ciroot:/home/zci/ZCIWorkspace
        environment:
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
            - CI_BUILDROOT=/home/zci/ZCIWorkspace
            - CI_ROOT=$CI_ROOT_VOLUME
            - CI_PRJ=s11ltss
        extra_hosts:
            dist.suse.de: $DIST_SUSE_DE
        build:
            context: .
            dockerfile: s11-latest.Dockerfile
            args:
                - CI_UID=${CI_UID}
                - CI_GID=${CI_GID}
            extra_hosts:
                dist.suse.de: $DIST_SUSE_DE
        profiles:
            - all
            - s11

volumes:
  ciroot:
