#! /usr/bin/python3
import sys, os, re
import subprocess

def writeln( f, l ):
    f.write( l )
    f.write( '\n' )

class PkgDef( object ):
    ''''''
    def __init__( self, pdef ):
        d = re.split( r'\s+', pdef )
        self.n = d[0]
        self.v = d[1]
        self.r = d[2]
        self.prv = []
        self.req = []
        self.obs = []
        self.con = []
        self.product = None

    def __str__( self ):
        return f'PKG({self.n}-{self.v}-{self.r})'

def buildPkg( pkgdef ):
    isProduct = pkgdef.product is not None

    with open( 'ptest.spec', 'w' ) as f:
        writeln( f, '%undefine vendor' )
        writeln( f, f'Name:           {pkgdef.n}' )
        writeln( f, f'Version:        {pkgdef.v}' )
        writeln( f, f'Release:        {pkgdef.r}' )
        writeln( f, 'Provides:        test42' )

        if isProduct:
            writeln( f, f'Provides:        product() = {pkgdef.product}' )
            writeln( f, f'Provides:        product({pkgdef.product}) = {pkgdef.v}-{pkgdef.r}' )

        for t,d in [ ('Provides', 'prv'), ('Requires', 'req'), ('Obsoletes', 'obs'), ('Conflicts', 'con') ]:
            d = getattr( pkgdef, d )
            for l in d:
                writeln( f, f'{t}:        {l}' )

        writeln( f, 'License:        nolicense' )
        writeln( f, 'Summary:        nosummary' )
        writeln( f, 'Vendor:         novendor' )
        writeln( f, 'BuildArch:      noarch' )
        writeln( f, 'BuildRoot:      /tmp/%{name}-%{version}-build' )
        writeln( f, '%description' )
        writeln( f, 'nodescription' )
        writeln( f, '%install' )
        writeln( f, 'rm -rf $RPM_BUILD_ROOT' )
        writeln( f, 'mkdir -p $RPM_BUILD_ROOT' )

        if isProduct:
            writeln( f, 'mkdir -p $RPM_BUILD_ROOT/etc/products.d/' )
            writeln( f, f'cat <<EOF >$RPM_BUILD_ROOT/etc/products.d/{pkgdef.product}.prod' )
            writeln( f, f'<?xml version="1.0" encoding="UTF-8"?>' )
            writeln( f, f'<product schemeversion="0">' )
            writeln( f, f'  <vendor>novendor</vendor>' )
            writeln( f, f'  <name>{pkgdef.product}</name>' )
            writeln( f, f'  <version>{pkgdef.v}</version>' )
            writeln( f, f'  <release>{pkgdef.r}</release>' )
            writeln( f, f'  <arch>noarch</arch>' )
            writeln( f, f'  <summary>Product:{pkgdef.product}-{pkgdef.v}-{pkgdef.r}</summary>' )
            writeln( f, f'</product>' )
            writeln( f, f'EOF' )

        writeln( f, '%files' )
        if isProduct:
            writeln( f, f'/etc/products.d/{pkgdef.product}.prod' )

    cmd = ["rpmbuild", "-bb", "ptest.spec"]
    ret = subprocess.run( cmd )#, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL )
    print( "===== rpmbuild", ret.args, "=>", ret.returncode )
    if ret.returncode != 0:
        raise Exception( 'Rpmbild error', pdef )


def parseRepoDef( rfile ):
    ret = []
    with open( rfile, 'r' ) as f:
        pdef = None
        for l in f:
            words = re.split( r'\s+', l.strip(), maxsplit=1 )
            print( words )
            if len(words) == 0:
                continue
            if len(words) == 1 and words[0] == '':
                continue
            if words[0][0] == '#':
                continue

            typ, dat = words

            if typ == 'Pkg:':
                if pdef is not None:
                    ret.append( pdef )
                pdef = PkgDef( dat )
            elif typ == 'Prd:':
                pdef.product = dat
            elif typ == 'Prv:':
                pdef.prv.append( dat )
            elif typ == 'Req:':
                pdef.req.append( dat )
            elif typ == 'Obs:':
                pdef.obs.append( dat )
            elif typ == 'Con:':
                pdef.con.append( dat )

            elif typ != '':
                raise Exception( 'Unknown line type', typ )
        else:
            if pdef is not None:
                ret.append( pdef )
    return ret

def main():
    argv = sys.argv[1:]
    rfile = argv[0] if len(argv) else "ptest.repo"
    pkgdefs = parseRepoDef( rfile )
    for pkgdef in pkgdefs:
        buildPkg( pkgdef )

if __name__ == '__main__':
    main()
