#! /bin/bash

LABELS="${LABELS:-head s15 s12sp3 s12sp2 s12sp1 s12 s11sp3}"

test -z "$1" && {
  echo "Usage: $(basename "$0") SCRIPT"
  echo "Execute SCRIPT (or command) on all CI hosts via ssh."
  echo "LABELS='$LABELS'"
  exit 1
}

for L in $LABELS; do
  SSH="ssh -x root@h_$L"
  HL="$($SSH cat zypp-ci-label)" || continue

  Becho "=====[$L]\t================================================================================"

  if [ -f "$1" ]; then
    scp "$1" root@h_$L:allHostsScript
    $SSH L=$L ./allHostsScript
  else
    $SSH "$@"
  fi
done
